# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0003_auto_20180210_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
    ]
